@extends('edifygoclass.layout')
@section('contents')

    <section class="breadcrumb-banner overlay" style="background-image: url('{{asset('edifygo_assets')}}/image/breadcrumb-banner.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="breadcrumb-title">Terms And Conditions</h2>
                </div>
            </div>
        </div>
    </section>

    <section class="static-content">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <p>These Terms & Conditions or (“Terms”) of use (a) terms of use ( ToU )along with the ( privacy policy) to use of our website <a href="https://www.oktat.in/" class="text-blue">www.oktat.in</a> (“Website”), our applications (“Application”)  or services in connection with the Application/, Website/ (“Services”) or (b) any modes of registrations or usage of services , including through SD cards, mobile or other storage/transmitting device ( defines hereinafter)  are between OKTAT EDUCATION SERVICE PRIVATE LIMITED (“Company/Owner/We/Us/Our”) and its users (User/You/student).</p>

                    <p>if you have any questions regarding the terms , you may Contact Us at 7211113006 / 07 or email at info@oktat.in</p>

                    <h5 class="static-title">Technicality of Terms</h5>
                    <p>These Terms install an electronic record in pursuance with the provisions of the Information Technology Act, 2000 and the Information Technology (Intermediaries guidelines) Rules, 2011 made under it, as rectified from time to time.</p>

                    <h5 class="static-title">Read Carefully</h5>
                    <p>Terms of use and the privacy policy of the Oktat (“Privacy Policy”) with respect to registration with us, the use of the Application, Website or Services discreetly or with Caution before using the Application, Website or Services. In the incident or event of any difference between the Terms and any other moralites with respect to the Application or Website or Services or, the provisions of the Terms and conditions shall predominate.Your use/access/browsing of the Application or Website or Services or registration (with or without payment/with or without subscription) through any means shall to inform us your assent of the Terms and Your agreement to be legally confined by the same way. If You do not consent with the Terms of use or the Privacy Policy, please do not use the Application or Website or benefit the Services. Any entry/access to our Services/Application/website through registrations/subscription/contribution  is non transferable.</p>

                    <p>Barring as described below, all information, content, course ,PDF file, Video URL, trademarks, services marks, trade names, and trade secrecy Inclusive but not limited to the software, text, images, graphics, video, script and audio, contained in the Application, Website and Services are possessory property of the Oktat (“possessory Information”). No possessory Information may be copied, downloaded, reproduced, modified, republished, uploaded, posted, transmitted or distributed in any way without obtaining before written assent from the Oktat and nothing on this Application or Website or Services shall be deemed to confer a license of or any other right, interest or title to or in any of the intelligential property rights concerned to the Oktat , to the User. ️You may personal the medium on which information/content/course  resides, but Oktat shall at all times inhibit full and complete title to the information/content/course and all intelligential property rights inserted by the Oktat on such medium. few contents on the Website may pertain to third parties. Such contents have been reproduced after taking prior consent from said party and all rights relating to such course /content will remain with such third party. Further, you identify and accept that the proprietorship of all trademarks, copyright, logos, service marks and other intelligential property owned by any third party shall continue a statement with such party and You are not permitted to use the same without the agreement of the respective third party.</p>

                    <h5 class="static-title">Restriction of activities while  to take advantage of our services</h5>
                    <p>Your use of our Website, Application and Services is exclusively for Your personal and non-commercial use. Any use of the Application, Website or Services or their content/course other than for personal purposes is forbidden.Your personal and non-commercial use of this Application, Website, or our Services will be subjected to the following restrictions or Users Will not endeavor or engage in any activity that may; </p>

                    <ol type="a">
                        <li>User can not decompile, reverse engineer, or disassemble the contents or extract the source codes of the Application/ Website and/or Service convert , copy, dispense, transmit, display, perform, reproduce, publish, license, create derivative works from, transfer, or sell out any information or software acquired from the Application/Website and/Services or remove any copyright, trademark registration, or other possessory notices from the contents of the Application/Website/Services.</li>
                        <li>User can not 
                            <ol type="i">
                                <li>use this Application/ Website/Services for commercial objective of any kind, or</li>
                                <li>advertise or sell the Application / Services / domain names or otherwise (whether or not for profit), or postulate others ( Inclusive , without limitation, avarice for contributions or donations) or use any Users forum for commercial purposes of any kind, or </li>
                                <li>use the Application /Website/ and Services in any way that is illegal, or disadvantage the Oktat or any other Users or persons or authority as laid down by the Oktat. </li>
                            </ol>
                        </li>
                        <li>constructing receivable any content that is Deceptive ,illegal ,detrimental, minatory, outrageous, Tyrannical ,disgraceful, Offensive, libelous, boorish, bawdy, child-pornographic, voluptuous, lascivious, unholy, invasive of another’s privacy, hateful, or racially, phyletic , ethnically or otherwise calamitous ,Stalking, threatening and/or harassing another and/or provoke other to commit violence; Transmitting material that stimulate anyone to commit a delinquent offence, that results in civil liability or otherwise infringement any contingent laws, regulations or code of practice; Intervene with any other User's use or happiness of the Application/Website/Services. </li>
                        <li>constructing , transmitting or collecting electronic copies of product/ content /course protected by copyright without the assent of the owner, by doing any act that amounts to the breach of intellectual property or making available any course that violate any intellectual property rights or other possessory rights of anyone else; Make available any content/course that You do not have a right to make available under any law or contractual or Believable relationship, unless You own or control the rights thereto or have received all necessary consents for such use of the content; hypocrisy of any Users or entity, or falsely state or otherwise misrepresent Your relevance  with a User or entity Post, transmit or make available any content / course that contains viruses, trojan horses, worms,ascarides, spyware, time bombs, cancelbots, or other computer programming routines, code, files or such other programs that may scathe the Application/services, interests or rights of other users or limit the functionality of any computer software, hardware or telecommunications, or that may harvest or produce or to collect any data or personal information about other Users without their permission. </li>
                        <li>use the Application/Website/Services/ in any manner that could lesion,Incapable , overburden or impair any of the Application’s/Website’s servers or the networks connected to any of the servers on which the Application/Website is hosted; Intentionally or unintentionally interfere with or breakdown the services or infringement any applicable laws related to the access to or use of the Application/Website/Services , infringement any needfulness, procedures, policies or regulations of networks connected to the Application/Website/Services, or engage in any activity prohibited by these Terms, Breakdown or interfere with the security of, or otherwise cause harm to, theApplication/ Website/ Services/ content/course, systems resources, or gain unpossessed access to user accounts, passwords, servers or networks connected to or accessible through the Application/Website/Services or any allied or linked sites.</li>
                        <li>intervene️ with, or prohibit any user from using and enjoying access to the Application/Website/Services, or other alliaed sites, or join or attached in disruptive attacks such as renege of service attack on the Application/Website/Services; utilize deep-links, page-scrape, robot, spider or other automatic device, program, algorithm or methodology, or any equal manual process, to increase traffic to the Application/Website/Services to reach, obtain, copy or monitor any portion of the Application/Website/Services or in any way to generate or deter the navigational structure or presentation of the Application, any articles ,to receive or attempt to receive any articles ,documents or information through any means not specifically made available through the Application/website /services;</li>
                    </ol>

                    <h5 class="static-title">Oktat Shall Play Following Role And Rights</h5>
                    <p>By submitting content on or through the Services (your “material ”), you give us a worldwide, non-exclusive, royalty-free license (with the right to sublicense) to use, copy, reproduce, regenerate, process,develop, adapt, convert, retouch, publish, manifest, transmit, display and distribute Such as material in any and all media or distribution methods (now known or later developed) and to allies your Material with you, except as described below. You agree that others may use Your material in the same way as any other material available through the Services. Other users of the Services may fork, tweak and repurpose your material in accordance with these Terms. If you delete your user account your Material and name may remain available through the Services.</p>

                    <p>Neither the Oktat nor any other parties provide any warranty or guarantee as to the accuracy, precision,timely, performance,completeness or suitability of the information and materials found or offered on Application/Website/Services for any particular purpose. You agree/accept that such information and Material may contain inaccuracies or errors and we expressly exclude liability for any inaccuracies or errors to the fullest extent/limit permitted by law. Oktat also reserves the right and discretion to make any changes/corrections or withdraw/add contents at any time without notice. In particular, but without limiting anything here, the Oktat anegate/disclaims any amenableness for any errors and accuracy of the information that may be contained in the Application/websites/services. In the preparation of the Application/Website/Services/and contents therein, every effort has been made to offer the most current, correct, and clearly expressed information possible. Nevertheless, inadvertent errors may occur. Our Website provides Users with access to compiled/to combines educational service information and related sources Such information is provided that We assume no liability for the accuracy or completeness or use or non obsolescence/Desuetude of such information. We shall not be liable to update or ensure continuity of such information contained on the Website. We would not be responsible for any errors, which might appear in such information, which is compiled from third party sources or for any unavailability of such information. From time to time the Website may also include links to other websites.These links are provided for your convenience to provide further information.They do not signify that we support the websites. We have no responsibility for the content of the linked websites.You may not create a link to the Website from another website or document without the Company’s prior written agreement. Any response/feedback from User is most welcome to make the Application and contents thereof error free and user friendly.</p>

                    <p>The content  of the Application/Services/websites are developed on the concepts covered in the structured course of study of the syllabus prescribed for students of various courses. The usage of the Application/Services/websites is not endorsed/supported as a substitution to the curriculum / courses based education provided by the educational institutions.The basic definitions and formulae of the subject matter would remain the same. The Oktat agree/accept, there are various means of Services structured Course pedagogy and inclusion of methods in the Application/Services/websites does not signify endorsement of any particular method nor exclusion signify disapproval. Subscription to the Application or usage of our Services/Website does not in any manner guarantee admission to any educational / academic institutions or passing of any exams or achievement of any specified percentage of marks in any examinations.</p>

                    <p>The Oktat reserves the right at its only/sole discretion to remove, review, edit or delete any content. Similarly, We will not be responsible or liable for any content uploaded by Users directly on the Website, irrespective of whether We have certified any answer uploaded by the User. We would not be amenable to verify whether such a content placed by any User contain infringing materials or not. Some parts of the Services are interactive, and we encourage contributions by Users, which may or may not be subject to editorial control prior to being posted. The Oktat accepts no responsibility or liability for any material / content communicated by third or other parties in this way. Certain course in the Application/Services/Website/ (in particular relating to assistance in preparations for administrative services) may contain opinions and views. The Oktat can not be amenable for such opinions or any claims resulting from them. Further, the oktat makes no warranties or representations whatsoever regarding the quality, content, completeness, or adequacy of such information and data.</p>

                    <p>By registering yourself , you agree to make your contact details available to Our employees, associates and partners so that you may be contacted for education information and promotions through mobile, SMS, email etc.The User expressly grants/give such permission to contact him/her through telephone, SMS, e-mail and holds the oktat atone/indemnified against any liabilities including financial penalties, damages, expenses in case the User’s mobile number is registered with Do not Call (DNC) database.The oktat may, based on any form of access to the application or Services or Website or registrations through any source whatsoever, contact the User through sms, email and call, to give information about its education as well as notifications on various important updates and/or to seek permission for demonstration of its Course/content. While the oktat may, based on the User’s confirmation, facilitate the demonstration of its content at the location sought by the User, the User acknowledges that he/she has not been induced by any statements or representations of any person with respect to the quality or conditions of the course / content and that User has relied exclusively on the investigations, examinations and inspections as the User has chosen to make and that the oktat has afforded the User the opportunity for full and complete investigations, examinations and inspections.</p>

                    <p>the oktat shall have the right to monitor and download and usage of the contents thereof by the buyer/student, to analyze such use and discuss the same with the user/student to enable effective and efficient usage of the Services. The User expressly permits the oktat to clear the doubts of the student using the application/service by answering the questions placed before it, providing study plans, informing of the progress, providing feedback, communicating with the student and mentoring the student through telephone or e-mail on express consent of the legal guardian/parent of the student / user or through any other forum. Access to certain constituent of the Services including doubt clearance, mentoring services etc may be subject to separate terms, conditions and fair usage policy. The oktat reserves the right to determine the criteria for provision of various constituent of Services to the different categories of Users based on its policies. Hence, subscription to the Application/service or registrations do not automatically entitle the User to any and all constituent of Services provided by the oktat and the oktat shall be entitled to exercise its discretion while providing access to and determining continuity of certain constituent of Services. We reserve the right to extend, cancel, discontinue, prematurely withdraw or modify any of Our Services at Our discretion.</p>

                    <p>The oktat's websites and / or Services, including the Application and content, are consistent only with certain devices/phones/instruments/hardware < . The oktat shall not be obligated to provide workable services for any instruments that are not recognized by the oktat or those instruments that may be purchased from any third party which are not consistent with the oktat’s Services. The oktat reserves the right to upgrade the table/ type of consistent devices as required from time to time.</p>

                    <p>Users have to specify the address to which the payment has to be made at the time of  access/joining in tution. Payment collector arrive directly to the address as specified at the time of joining/access in tuition class and You cannot, under any circumstances whatsoever, change the address after the joining/access is processed. In case of any change in the address, You need to specify the same to us in writing well in advance to the collecting date. Any inconsistencies in name or address will result in non-collecting of the Payment fees of tuition Class. In order to enter/access the Services and to advantages the use of the Application You shall be required to register yourself with the Application/Services/websites, and maintain an account with the Application/Services/websites.</p>

                    <p>*You will be required to furnish certain information and details, including Your name, mobile number, e-mail address, residential address, grade/class of the student, school name, payment information (credit/debit card details) if required, and any other information deemed necessary by the Application. With respect to the provision of information,The following can be addressed. :-</p>

                    <p>You agree that Your Capability / ability to use Your account is dependent upon external factors such as internet service providers and internet network availability and the oktat cannot guarantee accessibility to the Application at all times. In addition to the disclaimer mentioned in the conditions / Terms,  the oktat shall not be liable to You for any damages arising from Your inability to log into Your account and access the services of the Application at any time.You are responsible for maintaining the secrecy of the account information and for all activities that occur under Your account. You agree to </p>

                    <ol type="a">
                        <li>ascertain / ensure that You successfully log out from Your account at the end of each session; and </li>
                        <li>immediately notify the oktat of any unauthorized use of Your account. If there is reason to believe that there is likely to be a infringement of security or misuse of Your account, we may request You to change the password or we may suspend Your account without any liability to the oktat, for such period of time as we understand / deem appropriate in the circumstances. We shall not be liable for any loss or damage arising from Your failure to comply with this provision.It is Your only/sole responsibility to ensure that the account information provided by You is accurate, complete and latest.</li>
                    </ol>

                    <p>Users who are “able/competent/capable” of contracting within the meaning of the Indian Contract Act, 1872 shall be Suitable/eligible to register for the Application and all Our Services. Persons who are minors, un-discharged insolvents etc. are not eligible to register for Our Services. As a minor if You wish to use Our Services, such use shall be made available to You by Your legal guardian / trustee / parents, who has agreed to these Terms. In the event a minor utilizes the Application/Website/Services, it is assumed that he/she has obtained the agreement / consent of the legal guardian/ trustee / parents and such use is made available by the legal guardian / trustee / parents. The oktat will not be responsible for any consequence that arises as a result of misuse of any kind of Our Application or Services that may occur by virtue of any person including a minor registering for the Services provided. By using the Services You warrant that all the data provided by You is accurate and complete and that student using the Application has obtained the consent of parent/trustee legal guardian (in case of minors). The oktat reserves the right to finish Your subscription and / or refuse to provide You with access to the Services if it is discovered that You are under the age of 18 (eighteen) years and the consent / agree to use the Services is not made by Your parent/trustee legal guardian or any information provided by You is inaccurate. You agree that the oktat does not have the responsibility to ensure that You conform to the Aforementioned eligibility criteria. It shall be Your sole responsibility to ensure that You meet the required qualification. Any persons under the age of 18 (eighteen) should seek the consent of their parents/trustee legal guardians before providing any Information about themselves or their parents and other family members on the Application.</p>


                    <h5 class="static-title">Roles & Obligation /bondage Of Oktat & Buyer/student In Order To Avail The Services</h5>
                    <p>The Course and services: Subject to other provisions of this consent, student may join the tution owner may listing/register tuition classes sell services through the Website. For such join of student in tuition class and services, in addition to other applicable terms of the Agreement/consent, Tuition owner/ seller specifically agree to the roles and obligations of the student set out under Section of Terms. For marketing, sale and/or promotion of course and services through the Website, in addition to other applicable terms of the Agreement, [ Seller/ Tuition owner will be required to enter into a separate written agreement with oktat ]. Any joining into Tuition class / course and services through the Website will constitute a contract of joining between the student of such related course and services and the Seller/tution owner and services shall be delivered by such Seller/tution owner to such student directly. oktat can/shall not be responsible for, learning process, Material,  syllabus/course/tuition class, convenience, quality education, suitability and aptness of any service join or accessed using the Website. course/tuition class or Content in relation to Services; seller/ tution owner may create and/or display tuition class/course (including information regarding the offerings of syllabus, course, pictures,Fees, review, ratings and feedbacks) on the Website. By displaying any tuition class/course or Content on the Website, unless agreed to and provided for to the contrary, seller/ Tuition owner/student /user grants oktat a right to use such tuition class /course or content in any manner.  User/ student shall paying tuition class /course and services from Sellers/ tuition owner through the Website at the fees/price provided therein. User acknowledge that such paying of tuition class /course and services is being made directly from the Seller/tution owner through the Website and oktat is only providing a platform for the users /student and Sellers/tution owner to interact online with respect to such sale/offer/discount through the Website.</p>

                    <p>Users acknowledge that Services only include providing an online platform for displaying, Booking,marketing, buying, Joining and promoting education related Tution class/course for providing Learning Services like tuition class/course, Any sale transaction made between a users/students and a Seller/tuition owner shall constitute an agreement of sale between such User Student and Seller/tuition owner. and oktat shall have no liability with respect to quality, appropriateness, merchantability, authenticity and accuracy of the services sold or provided through the Website. In the event of Your infringement of these Terms, You agree that the oktat will be irreparably harmed and may not have an adequate remedy in money or damages.The oktat therefore, shall be entitled in such event to obtain an injunction against such a infringement from any court of competent jurisdiction... The oktat’s right to obtain such relief shall not limit its right to obtain other treatment or remedies. The oktat, oktat’s officers, directors, employees, affiliates and agents and any other service provider responsible for providing Services in connection with this Agreement will not be liable for any acts or omissions, including of a third or other party, and including those vendors participating in oktat's offerings made to Users, or for any unauthorized interception of data or breaches of this Agreement attributable in part to the acts or omissions of third or other parties, or for damages associated with oktat, or equipment that it does not furnish, or for damages that result from the operation systems, equipment, facilities or services provided by third parties that are interconnected with oktat. </p>

                    <h5 class="static-title">Limitation Of Liability & Indemnification</h5>
                    <p>You agree to defend, indemnify and hold harmless the oktat, its officers, directors, employees and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney’s fees) arising from:</p>

                    <ol type="a">
                        <li>Your use of and access of the Application/Website/Services;</li>
                        <li>Your violation of any term of these Terms or any other policy of the oktat and under applicable law ; </li>
                        <li>Your violation of any third party right, including without limitation, any copyright, property, or privacy right; or </li>
                        <li>any claim that Your use of the Application/Website/Services has caused damage to a third party. This defense and indemnification obligation will survive these Terms. In no event shall the oktat , its officers, directors, employees, partners or agents be liable to You or any third party for any special, incidental, indirect, consequential or punitive damages whatsoever, including those resulting from loss of use, data or profits or any other claim arising out, of or in connection with, Your use of, or access to, the Applicaton.</li>
                    </ol>

                    <p>Any breach/violation by Users of the terms of this Clause may result in immediate suspension or termination of Your Accounts apart from any legal treatment/remedy that the oktat can avail. In such instances, the oktat may also disclose Your Account Information if required by any Governmental or legal authority. You understand that the breach/violation of these Terms could also result in civil or delinquent or criminal liability under applicable laws. Each User is responsible for any breach of its obligations under the Agreement and/or for the consequences of any such breach. The Terms shall be governed by and construed in accordance with the laws of India, without regard to conflict of law principles. Further, the Terms shall be subject to the sole /exclusive jurisdiction of the competent courts located in Surat ( Gujarat ) and You therefore concur to and accept the jurisdiction of such courts. The oktat has the right to change modify, convert,  retouch, suspend, or discontinue and/or eliminate any aspects, features or functionality of the Application or the Services as it understand/deems fit at any time without notice. Further, the oktat has the right to rectify these Terms from time to time without prior notice to you. The oktat makes no commitment, express or implied, to maintain or continue any aspect of the Application. You agree that the oktat shall not be liable to You or any third party for any modification, revisal , adjournment, suspension ,Termination or discontinuance of the Application/Services. All prices are subject to change without notice.</p>


                    <h5 class="static-title">Conclusion Of Oktat</h5>
                    <p>User is obligate/bound by the consent/Agreement from the time such User commences using the Services till the time such User ceases to use Services. Notwithstanding anything else contained herein, all the rights and obligations of Users under this Agreement, which either expressly or by their nature survive the Conclusion of this Agreement, shall not be extinguished by conclusion of this Agreement.User may conclusion this Agreement by ceasing access to Services in any manner, including disabling access to Registered Services. oktat may conclusion this Agreement with respect to any User by suspending or permanently barring access to Services. Oktat reserves the right to conclusion Users’ access to Services or any part of Services, at any time if: </p>

                    <ol type="a">
                        <li>such User, knowingly or unknowingly, causes direct or indirect breach, as ascertained by oktat, of these Terms or Privacy Policy or any part of the Agreement;</li>
                        <li>such User does not pay the requisite cost of using such part of Services which is not provided by oktat free of cost and is paid in nature; </li>
                        <li>a third party (if any) with whom oktat offers Services has conclusions its relationship with oktat or ceased to offer the related services to oktat or to such User; </li>
                        <li>provision of Services or any part of Services is no longer commercially viable or possible for oktat ; </li>
                        <li>oktat believes that such User is a repeat infringer of the terms of this Agreement; or oktat is required to conclusion this Agreement by applicable law, government order or order of a court with requisite jurisdiction.</li>
                        <li>Upon conclusion of this Agreement with respect to a User, all the legal rights, obligations and liabilities that such User and oktat have benefited from, been subject to (or which have accrued over time whilst the Agreement has been in force) or which are expressed to continue indefinitely, shall be unaffected by this cessation, and shall continue to apply to such rights, obligations and liabilities indefinitely.</li>
                    </ol>

                    <div class="main-title mt-5">
                        <h2>Common Provisions</h2>
                    </div>

                    <h5 class="static-title">Notice To Users</h5>
                    <p>All notices served by the oktat shall be provided via email to Your account or as a general notification on the Application. Any notice to be provided to the oktat should be sent to support@oktat.com</p>

                    <h5 class="static-title">Whole Consent</h5>
                    <p>The Terms of use , along with the Privacy Policy, and any other instructions made applicable to the Application from time to time, constitute the whole consent or agreement between the oktat and You with respect to Your access to or use of the Application, Website and the Services thereof.</p>

                    <h5 class="static-title">Entrust Mentioned</h5>
                    <p>Users cannot entrust or otherwise transfer Your devour or obligations under the Terms, or any right granted hereunder to any third party. The oktat’s rights under the Terms are freely transferable by the oktat to any third parties without the requirement of seeking Your consent.</p>

                    <h5 class="static-title">Seriousness or Severability</h5> 
                    <p>If for any reason, any rule / court of competent jurisdiction, or any part of it gets any provision of unrecoverable, then that provision will be extended to the maximum extent so that the intentions of the parties can be reflected by these provision. Those provisions and the remaining conditions will continue in full force and effect.</p>

                    <h5 class="static-title">Renunciation</h5> 
                    <p>Any failure by the oktat to apply or enforce or exercise any provision of the Terms of use , or any related right, shall not build / constitute a renunciation by the oktat of that provision or right.</p>

                    <h5 class="static-title">Propinquity or Relation</h5> 
                    <p>You agree / acknowledge that Your partaking / participation on the Application, does not make You an employee or agency or partnership or joint venture or franchise of the oktat.</p>
                    
                    <p>The oktat provides these Terms of Use so that You are informed / aware of the terms that apply to your use of the Website/Application and Services. You acknowledge / agree that, the oktat has given You a proper opportunity to scrutiny these Terms of use and that You have consentient/ agreed to them.</p>

                    <h5 class="static-title">DISCLAIMER</h5> 
                    <p>THIS WEBSITE, THE APPLICATION AND THE SERVICES ARE PROVIDED ON  BASIS WITH ALL FAULTS AND WITHOUT ANY WARRANTY OF ANY KIND. THE OKTAT HEREBY DISCLAIMS / NEGATE ALL WARRANTIES AND CONDITIONS WITH REGARD TO THE WEBSITE, APPLICATION AND THE SERVICES, INCLUDING WITHOUT LIMITATION, ALL IMPLIED WARRANTIES AND CONDITIONS OF COMMERCIALISM , MERCHANTABILITY, COURSE FOR A PARTICULAR PURPOSE, TITLE, ACCURACY, TIMELINESS. PERFORMANCE, COMPLETENESS, SUITABILITY AND NON-INFRINGEMENT. ADDITIONALLY, THE OKTAT SHALL NOT BE RESPONSIBLE / LIABLE FOR ANY DAMAGES ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS WEBSITE, OR THE APPLICATION OR THE SERVICES OR FROM DOWNLOADING ANY CONTENT OR WATCHING VIDEO. YOUR USE OF ANY INFORMATION OR MATERIALS OR COURSE ON THIS WEBSITE/APPLICATION/SERVICES IS ENTIRELY AT YOUR OWN RISK, FOR WHICH WE SHALL NOT BE RESPONSIBLE / LIABLE. IT SHALL BE YOUR OWN RESPONSIBILITY TO ENSURE THAT SERVICES PROVIDED BY US MEET YOUR SPECIFIC REQUIREMENTS.</p>
                </div>
            </div>
        </div>
    </section>
@endsection